[[categories]]
name = "git"
command = ["test", "-d", ".git"]

[[categories.status]]
name = "clean"
command = ["git", "status", "--porcelain"]

[[categories.status]]
name = "unpushed"
command = ["git", "log", "--branches", "--not", "--remotes"]
command2 = '''
if [ -n "$(git log --branches --not --remotes)" ]; then
    echo "unpushed"
fi
'''

[[categories.stats]]
name = "size"
command = ["nu", "--commands", "du . | first | get physical"]
